		
		<nav class="navContact">
			<ul>
				<li><a href="http://www.webfiction-eldinn.com/" target="_blank" >Encyclopédie de l'univers</a></li>
				<li><a href="https://github.com/eldinn" target="_blank" >GitHub du projet</a></li>
				<li><a href="https://www.facebook.com/M.Boreatti/" target="_blank" >Page Facebook</a></li>
				<li><a href="http://boreatti.deviantart.com/" target="_blank" >Profil DeviantArt</a></li>
			</ul>
		</nav>

	</div>
</div>


</div>
<div class='containerButonBottom'>
	  

	<div class="containerOneButton">
	    <p>Replier le menu</p>   
		<div id="rpP"></div>
		<div class="containerElement" id="btnRepli">	 
			<img class="image2"  src="img/butonShowMenuHover.png" alt=""> 
	    	<img class="image1" id="rpImg"  src="img/butonShowMenu.png" alt="">
		</div>
	</div>

	<div class="containerOneButton">
		<a href="../menuPrincipal.php">Retour à la vue principale</a>  
		<div class="containerElement" id="btnretour">  
			<img class="image2"  src="img/butonShowMenuHover.png" alt=""> 
		    <img class="Image1" id="rtImg"  src="img/butonShowMenu.png" alt="">
		 </div>
	 </div>

</div>