<!DOCTYPE HTML />  
<html>
<head>
	<meta charset="utf-8" />
	<title><?=$partTitre['titre'] ?></title>

	<link type="text/css" rel="stylesheet" href="menuParties.css" />
	  <?php include('customCSS.phtml') ?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<!-- <script src="jquery-2.1.4.min.js"></script> -->
	<script src="scriptParties.js" ></script>
	<script type="text/javascript">
		/********************************************************   
		----- - PRELOAD -   ---- 
		******************************************************/
		var p = 0;
		$.arrPreload = [];
		$.arrPreload[p++] = "<?=$partImg['image'] ?>";
		$.arrPreload[p++] = "img/bgMenus2.png"


		$(document.createElement('img')).bind('load', function () {
		  if ($.arrPreload.length > 0)
		    this.src = $.arrPreload.shift()
		  else
		    preloadDone();
		}).trigger('load');

		function preloadDone(){
		  setTimeout(function () {
		    $("#oLoading").html("").fadeOut();
		  }, 300);

		};
	</script>


</head>

<body>

<div id="oLoading"><div><img src="../img/loading5.gif" alt="Vous voyagez hors de la matière..." /></div></div> 
<!-- <audio id="audioPlayer" src="<?=$partZik['musique'] ?>" ontrols loop="-1" autoplay></audio>
<img id="controlSon" src="../img/iconSonActive.png" onclick="play('audioPlayer', this)"> -->
</br></br>


<div class="menuChapitres">
	<div class="containChapitres">
	
		<?php if($erreur) : ?>
         <h1><?= $erreur ?> </h1>
         <?php else : ?>
		
		<h1><?=$partTitre['titre'] ?> - Partie <?=$partNum['numero'] ?></h1>
		<p class="aPropos">A propos du lieu </p> 
		<p class="desc"><span style="font-weight:bold;"><?=$partPropos['aPropos'] ?></span>
		</br><?=$partDesc['description'] ?> </p>

		 <nav class="navChapitres">
			<ul>
			<?php foreach($listeChpPartie as $key => $chapitre):?> 
				<li><a href='../chapitres/chapitre.php?id=<?= $chapitre['id'] ?>'><img src="img/<?= $chapitre['image'] ?>"></img> </br> <h2><?= $chapitre['titre'] ?></h2></a></li>
			<?php endforeach ?>
			</ul>
		</nav>
        <?php endif ?>  
<?php include('boutons.phtml');?>


</body>

</html>