
<style type="text/css"> 
	@import url('https://fonts.googleapis.com/css?family=Roboto');
	@import url('https://fonts.googleapis.com/css?family=Bahiana|Dorsa|Orbitron|The+Girl+Next+Door');
	@import url('https://fonts.googleapis.com/css?family=Abel|Exo|Exo+2|Khand|Work+Sans|Yanone+Kaffeesatz');

	body{
		width: 80%;    
		height:100%;     
		font-family: 'Roboto', sans-serif; 
		margin:0 auto; 
	} 

	img{
		width: 20%;
	}

	<?= $chp['css'] ?>

</style>